// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7GW81sib48ndtplh4BLf1kBpRRJfVFtY',
    appId: '1:1053607258461:web:0499445b2f7eb1e4b9a0b4',
    messagingSenderId: '1053607258461',
    projectId: 'evaluacion-be718',
    authDomain: 'evaluacion-be718.firebaseapp.com',
    storageBucket: 'evaluacion-be718.firebasestorage.app',
    measurementId: 'G-C1ZN887F5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwftU411Z8sQ69vakrC3d4Lhjyv9QMCco',
    appId: '1:1053607258461:android:b2126d32ff4c16e8b9a0b4',
    messagingSenderId: '1053607258461',
    projectId: 'evaluacion-be718',
    storageBucket: 'evaluacion-be718.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7GW81sib48ndtplh4BLf1kBpRRJfVFtY',
    appId: '1:1053607258461:web:9e201abf2d8e5827b9a0b4',
    messagingSenderId: '1053607258461',
    projectId: 'evaluacion-be718',
    authDomain: 'evaluacion-be718.firebaseapp.com',
    storageBucket: 'evaluacion-be718.firebasestorage.app',
    measurementId: 'G-7G82EBX6WF',
  );

}